version: "3.8"

volumes:
  db_data:
    driver: local
  
  redis-data: 
    driver: local

  etcd-data: 
    driver: local

services:
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: chapp_room_postgres
    hostname: chapp_room_postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${CHAPP_POSTGRES_DB}
      - POSTGRES_USER=${CHAPP_POSTGRES_USER}
      - POSTGRES_PASSWORD=${CHAPP_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis: 
    image: redis:7.4.1-alpine3.20 
    container_name: chapp_room_redis
    hostname: chapp_room_redis
    ports: 
      - "6379:6379" 
    volumes: 
      - redis-data:/data
  
  etcd:
    image: quay.io/coreos/etcd:v2.3.8
    container_name: etcd
    networks:
      - etcd-net
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_NAME=etcd
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-single-node
    volumes:
      - etcd-data:/etcd-data

  nats:
    image: nats:2.10.22-scratch
    container_name: nats
    networks:
      - nats-net
    ports:
      - "4222:4222"  # Client connections
      - "6222:6222"  # Cluster connections
      - "8222:8222"  # Monitoring
    environment:
      - NATS_CLUSTER_ADVERTISE=nats
      - NATS_SERVER_NAME=nats-server
      - NATS_MONITORING_PORT=8222