room:
  name: exchange_service_monolith_app
  version: 0.0.1
  host: 0.0.0.0
  port: 8088
  secret: gholigholigholigholigholi
  auth_exp_min: 5,
  auth_exp_refresh_min: 5

postgres:
  db: postgres
  user: developer
  password: 123456
  host: 127.0.0.1
  port: 5432
  timezone: UTC
  sslmode: disable
  schema: null